# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Jooho Jeong
#tagline:             Programmer
description:         'Software engineer, Junior year of DigiPen Insitute of Technology'
url:                 'http://jooho556.github.io'
baseurl:             ''
paginate:            5
excerpt_separator: <!--more-->

# About/contact
author:
  name:              Jooho Jeong
  url:               https://jooho556.github.io
  email:             jooho556@gmail.com

# Collection
collections:
  projects:
    output: true
    
